services:
  embedding-app:
    build: ./embedding
    ports:
      - "${EMBEDDING_APP_PORT}:${EMBEDDING_APP_PORT}"
    depends_on:
      - postgresql
    environment:
      - DATABASE_URL=postgresql://${POSTGRESS_USERNAME}:${POSTGRESS_PASSWORD}@postgresql:5432/${POSTGRESS_DBNAME}
  chatbot:
    build: ./chatbot
    ports:
      - "${CHAT_APP_PORT}:${CHAT_APP_PORT}"
    environment:
      - DATABASE_URL=postgresql://${POSTGRESS_USERNAME}:${POSTGRESS_PASSWORD}@postgresql:5432/${POSTGRESS_DBNAME}
    depends_on:
      - postgresql
  postgresql:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: ${POSTGRESS_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESS_PASSWORD}
      POSTGRES_DB: ${POSTGRESS_DBNAME}
    volumes:
      - postgresql_data:/var/lib/postgresql/data       
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgresql
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgresql_data:
  pgadmin_data: